/* Generated By:JavaCC: Do not edit this line. GLParser.java */
package kr.ac.uos.ai.arbi.model.parser;

import java.util.*;
import java.io.*;
import kr.ac.uos.ai.arbi.model.*;

public class GLParser implements GLParserConstants {
        private static final Expression[] NULL_EXPRESSION = new Expression[0];

        public GLParser() {
                this(new StringReader(""));
        }

        public synchronized GeneralizedList parseGL(String glString) throws ParseException {
                ReInit(new StringReader(glString));
                return parseGL();
        }

  final private GeneralizedList parseGL() throws ParseException {
        Token id;
        Expression[] expressions;
    jj_consume_token(27);
    id = jj_consume_token(IDENTIFIER);
    expressions = parseExpressionList();
    jj_consume_token(28);
                {if (true) return GLFactory.newGL(id.image, expressions);}
    throw new Error("Missing return statement in function");
  }

  final private Expression[] parseExpressionList() throws ParseException {
        Expression expression;
        List<Expression> expressionList = new LinkedList<Expression>();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
      case INTEGER:
      case FLOAT:
      case VARIABLE:
      case SPECIAL_KEYWORD:
      case 27:
      case 29:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      expression = parseExpression();
                        expressionList.add(expression);
    }
                {if (true) return expressionList.toArray(NULL_EXPRESSION);}
    throw new Error("Missing return statement in function");
  }

  final private Expression parseExpression() throws ParseException {
        Value value;
        Variable variable;
        Function function;
        GeneralizedList gl;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case INTEGER:
    case FLOAT:
    case SPECIAL_KEYWORD:
      value = parseValue();
                {if (true) return GLFactory.newExpression(value);}
      break;
    case VARIABLE:
      variable = parseVariable();
                {if (true) return GLFactory.newExpression(variable);}
      break;
    case 29:
      function = parseFunction();
                {if (true) return GLFactory.newExpression(function);}
      break;
    case 27:
      gl = parseGL();
                {if (true) return GLFactory.newExpression(gl);}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Value parseValue() throws ParseException {
        Token id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER:
      id = jj_consume_token(INTEGER);
                {if (true) return GLFactory.newValue(Integer.valueOf(id.image).intValue());}
      break;
    case FLOAT:
      id = jj_consume_token(FLOAT);
                {if (true) return GLFactory.newValue(Float.valueOf(id.image).floatValue());}
      break;
    case STRING:
      id = jj_consume_token(STRING);
                {if (true) return GLFactory.newValue(id.image);}
      break;
    case SPECIAL_KEYWORD:
      id = jj_consume_token(SPECIAL_KEYWORD);
                {if (true) return GLFactory.newValue(id.image);}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Variable parseVariable() throws ParseException {
        Token id;
    id = jj_consume_token(VARIABLE);
                {if (true) return GLFactory.newVariable(id.image);}
    throw new Error("Missing return statement in function");
  }

  final private Function parseFunction() throws ParseException {
        Token id;
        Expression[] expressions;
    jj_consume_token(29);
    id = jj_consume_token(IDENTIFIER);
    expressions = parseExpressionList();
    jj_consume_token(28);
                {if (true) return GLFactory.newFunction(id.image, expressions);}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public GLParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2ec00008,0x2ec00008,0x4c00008,};
   }

  /** Constructor with InputStream. */
  public GLParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GLParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GLParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public GLParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GLParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public GLParser(GLParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(GLParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[30];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 30; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
