/* Generated By:JavaCC: Do not edit this line. GLParserConstants.java */
package kr.ac.uos.ai.arbi.model.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 1;
  /** RegularExpression Id. */
  int STRING = 3;
  /** RegularExpression Id. */
  int ws = 10;
  /** RegularExpression Id. */
  int delim = 11;
  /** RegularExpression Id. */
  int letter = 12;
  /** RegularExpression Id. */
  int digit = 13;
  /** RegularExpression Id. */
  int charac = 14;
  /** RegularExpression Id. */
  int EXP = 15;
  /** RegularExpression Id. */
  int colon = 16;
  /** RegularExpression Id. */
  int SIGN = 17;
  /** RegularExpression Id. */
  int number0 = 18;
  /** RegularExpression Id. */
  int number1 = 19;
  /** RegularExpression Id. */
  int number2 = 20;
  /** RegularExpression Id. */
  int hexa0 = 21;
  /** RegularExpression Id. */
  int INTEGER = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int VARIABLE = 25;
  /** RegularExpression Id. */
  int SPECIAL_KEYWORD = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WS>",
    "\"\\\"\"",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "\"\\\\t\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\f\"",
    "<token of kind 9>",
    "<ws>",
    "<delim>",
    "<letter>",
    "<digit>",
    "<charac>",
    "<EXP>",
    "\":\"",
    "<SIGN>",
    "<number0>",
    "<number1>",
    "<number2>",
    "<hexa0>",
    "<INTEGER>",
    "<FLOAT>",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "\"-->\"",
    "\"(\"",
    "\")\"",
    "\"#(\"",
  };

}
